### ISSUE TITLE
Miguel's Peer Code-Review on 8/30/2022

### ISSUE THREAD

**Issue by Jhaman1895** [shinyenyi/myPortfolio#10]
## Peer Code Review

- Here our team consisting of Ashwin, Kenny, and Jha conducted a peer code review for Miguel's  personal portfolio project.

**Comment by AshwinCarvalho999** [comment]
Please change the background images for the grid card layout.

**Comment by Jhaman1895** [comment]
I suggest that you fix the compatibility issues with the firefox browser (for example, the "see projects" button on card 1 of the works section).

**Comment by kene-creator** [comment]
I think if you make it functional on firefox to accommodate users that use that it would improve your project. Other than that its a well done project✔😎
