### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by jaamanu** [shinyenyi/myPortfolio#12]
- the work is clean and well organise
- outline needs to be remove
- the gap between the social media handles

**Comment by DaveZag** [comment]
Hi Miguel, Your work is great😃. Here are some suggestions for you to consider :
- On hover, the cards' background takes a while to change.
- Consider adding a __" Cursor: Pointer"__ to all buttons on the hover state.
- Consider also using the correct font-family for the card tags which is 'Inter' Normal.
- And last, you should add a different color to the links(nav and social media) when a user hovers over them. <br>
### Keep up the great work!🎉
